name: Test StyLua
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test_default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test (default)
        run: cargo test
