name: Stylua check

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "rework-healmodes-and-max-HPS" ]
  pull_request:
    branches: [ "rework-healmodes-and-max-HPS" ]

jobs:
    stylua:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Run Stylua check
              uses: JohnnyMorganz/stylua-action@v3
              with:
                  # token is needed because the action allegedly downloads binary from github releases
                  token: ${{ secrets.GITHUB_TOKEN }}
                  # CLI arguments
                  args: --check .
                  version: latest # NOTE: we recommend pinning to a specific version in case of formatting changes
                  #run: stylua
