name: Stylua check

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "rework-healmodes-and-max-HPS" ]
  pull_request:
    branches: [ "rework-healmodes-and-max-HPS" ]

jobs:
  integration:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: stylua
      uses: JohnnyMorganz/stylua-action@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        version: latest # NOTE: we recommend pinning to a specific version in case of formatting changes
        args: -g '*.lua' -- .
    - name: Apply Actions
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - name: Apply Actions 2
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: stylua formatting
 #----------samples-----------------------------------
 #   - name: Setup luarocks
 #     uses: leafo/gh-actions-luarocks@v4
 #
 #   - name: Setup tools
 #     shell: bash
 #     run: |
 #       sudo apt install -y curl unzip --no-install-recommends
 #       bash ./utils/install_stylua.sh
 #       luarocks install luacheck
 #       luarocks install vusted
 #   - name: Run tests
 #     shell: bash
 #     run: make integration
 #
 #   - name: Run tests
 #     shell: bash
 #     run: stylua
 #----------------------------------------------------
 
 #-----------samples----------------------------------
 # name: Lint
 #
 # on: [push, pull_request]
 #
 # jobs:
 #     lint:
 #        name: Luacheck
 #        runs-on: ubuntu-latest
 #        steps:
 #            - uses: actions/checkout@v2
 #            - name: Setup
 #              run: |
 #                  sudo apt-get update
 #                  sudo apt-get install luarocks
 #                  sudo luarocks install luacheck
 #            - name: Lint
 #              run: luacheck lua/ --globals vim
 #-----------------------------------------------------


# Configuration
# git: .gitattributes, .gitignore
# stylua: args: in yml, .styluaignore, .stylua.toml
# git-auto-commit-action: action.yml
## pre-commit: .pre-commit-config.yaml

# Used tools
# https://github.com/JohnnyMorganz/stylua-action (GitHub action for StyLua)
# https://github.com/JohnnyMorganz/StyLua (An opinionated Lua code formatter)
# https://github.com/stefanzweifel/git-auto-commit-action (directly commit formatting)

# Useful tools
# https://docs.github.com/ru/actions/learn-github-actions/understanding-github-actions
# https://github.com/peter-evans/create-pull-request (open a pull request with fixed formatting)
#
# https://pre-commit.com (A framework for managing and maintaining multi-language pre-commit hooks.)
# https://github.com/marketplace/actions/wow-packager (release.sh generates an addon zip file from a Git, SVN, or Mercurial checkout.)
# https://github.com/luarocks/lua-style-guide
# https://github.com/luarocks/luarocks/wiki/Installation-instructions-for-Windows
# https://github.com/Benjamin-Dobell/IntelliJ-Luanalysis


